Flipklok: Code/include/stepperAdvance.h File Reference
stepperAdvance.h File Reference
#include <msp430.h>
#include "pins.h"
#include <stdbool.h>
Macros
#define stepperTimeOffsetSlow 0x800;
#define stepperTimeOffsetFast 0x100;
Functions
void setupTimer0 ()
void stepperAdvance ()
Variables
bool timerCompareStepperSpeedToggle
Macro Definition Documentation
stepperTimeOffsetFast
#define stepperTimeOffsetFast 0x100;
Definition at line 15 of file stepperAdvance.h.
Referenced by ISR_TA0().
stepperTimeOffsetSlow
#define stepperTimeOffsetSlow 0x800;
Definition at line 14 of file stepperAdvance.h.
Referenced by ISR_TA0(), and setupTimer0().
Function Documentation
setupTimer0()
void setupTimer0 ()
Setup of timer0, uses the the ACLK (Auxiliary clock), counts up continuous. Capture control registers
CCR0
CCR1 triggers pwm LED
CCR2 triggers stepperAdvance()
TAIFG start reading ADC
Definition at line 26 of file timer.c.
{
    //Timer setup
    TA0CTL = TASSEL_1 | MC_2| TACLR | TAIE | ID_0;    // Set to counter to ACLK, Continuous clock, clear counter of clock, Enable TAIFG interrupt, Divider set to 1
    TA0CCTL1 = CCIE;                // TACCR1 interrupt enabled
    TA0CCTL2 &= ~CCIE;                // TACCR2 interrupt disable
    TA0CCR2 = stepperTimeOffsetSlow;             // compare at stepperOffset
    TA0CCR1 = pwmPeriod_cycles;
}
References pwmPeriod_cycles, and stepperTimeOffsetSlow.
Referenced by main().
stepperAdvance()
void stepperAdvance ()
Definition at line 23 of file stepperAdvance.c.
{
    if (P1IN & BIT0) // if 5V converter is on turn stepper
    {
        toggleCalculateTimeDifference = 0;          // disable triggering time difference function in timer interrupt.
        static unsigned int coil;
        if (stepsRemaining > 0 || toggleFwdInterrupt == 1)
        {
            P2OUT &= ~(STEPPER1 + STEPPER2 + STEPPER3 + STEPPER4);
            P2OUT |= stepperArray[coil];
            if (coil == 3)
            {
                P2OUT |= stepperArray[0];
            }
            else
            {
                P2OUT |= stepperArray[coil + 1];
            }
            coil++;
            if (coil == 4)
            {
                P2OUT |= stepperArray[0];
                coil = 0;
            }
            if (toggleFwdInterrupt == 0)
            {
                stepsRemaining--;
                mechanicalTimeFloat = mechanicalTimeFloat + timePerStep; //Increment mechanical time keeping counter with 1 step time
                if(mechanicalTimeFloat > 86400)
                {
                    mechanicalTimeFloat = 0; //reset after 24:00
                    #ifdef UART_ENABLED
                        UART_SendString("mechTime reset\r\n");
                    #endif
                }
                if((stepsRemaining > 999) && (0 == (stepsRemaining % 1000))) //every 1000 steps print steps remaining
                {
                    #ifdef UART_ENABLED
                        UART_SendString("s: ");
                        UART_SendUint32(stepsRemaining);
                        UART_SendString(", MTC: ");
                        UART_SendTime(mechanicalTimeFloat);
                        UART_SendString("\r\n");
                    #endif
                }
            }
        }
        else
        {
            TA0CCTL2 &= ~CCIE;                          // TACCR2 interrupt stepperAdvance disable
//            storeTime((uint32_t)mechanicalTimeFloat); // Store the current state of the clock in non volatile flash
            write_SegD((uint32_t)mechanicalTimeFloat);
            toggleCalculateTimeDifference = 1;          // enable triggering time difference function in timer interrupt.
            toggleFwdInterruptISR = 1;                     // Enable fwdButton interrupt again (disabled in timekeeping function when it is syncing)
        }
    }
}
References mechanicalTimeFloat, STEPPER1, STEPPER2, STEPPER3, STEPPER4, stepperArray, stepsRemaining, timePerStep, toggleCalculateTimeDifference, toggleFwdInterrupt, toggleFwdInterruptISR, UART_SendString(), UART_SendTime(), UART_SendUint32(), and write_SegD().
Referenced by ISR_TA0().
Variable Documentation
timerCompareStepperSpeedToggle
bool timerCompareStepperSpeedToggle
Definition at line 17 of file stepperAdvance.h.
Referenced by calculateTimeDifference(), ISR_TA0(), and port2ISR().