Flipklok: Code/include/uart.h File Reference
uart.h File Reference
#include <msp430.h>
#include <stdint.h>
Macros
#define UART_ENABLED
Functions
void UART_Init (void)
Setup UART communication, gets called from main()
void UART_SendChar (char c)
send a single character via UART to host system
void UART_SendString (char *str)
send a full string to host system
void UART_SendUint32 (uint32_t num)
send a 32 bit integer to host system
void UART_SendInt (int32_t num)
send a 16 bit integer to host system
void UART_SendTime (uint32_t seconds)
Sends a time formated in hours and minutes to host system.
Macro Definition Documentation
UART_ENABLED
#define UART_ENABLED
Definition at line 13 of file uart.h.
Function Documentation
UART_Init()
void UART_Init (void)
Setup UART communication, gets called from main()
Returns
void
Definition at line 18 of file uart.c.
{
    #ifdef UART_ENABLED
        P1SEL |= BIT1 + BIT2;   // Set P1.1 (RX) and P1.2 (TX) for UART function
        P1SEL2 |= BIT1 + BIT2;
        UCA0CTL1 |= UCSSEL_2;   // Use SMCLK
        UCA0BR0 = 13;          // 2400 baud rate
        UCA0BR1 = 0;
        UCA0MCTL = UCBRS0;      // Modulation UCBRSx = 1
        UCA0CTL1 &= ~UCSWRST;   // Initialize USCI state machine
    //    IE2 |= UCA0RXIE;        // Enable RX interrupt
    #endif
}
Referenced by main().
UART_SendChar()
void UART_SendChar (char c)
send a single character via UART to host system
Parameters
c,the character to send
Returns
void
Definition at line 38 of file uart.c.
{
    #ifdef UART_ENABLED
        while (!(IFG2 & UCA0TXIFG));  // Wait until buffer is empty
        UCA0TXBUF = c;  // Send character
    #endif
}
Referenced by UART_SendInt(), UART_SendString(), and UART_SendUint32().
UART_SendInt()
void UART_SendInt (int32_t num)
send a 16 bit integer to host system
Parameters
num,the integer to send
Returns
void
Definition at line 66 of file uart.c.
{
    #ifdef UART_ENABLED
        char buffer[12];  // Enough for "-2147483648\0"
        int i = 0;
        uint8_t isNegative = 0;
        if (num < 0)
        {
            isNegative = 1;
            num = -num;
        }
        // Convert integer to string (reverse order)
        do
        {
            buffer[i++] = (num % 10) + '0';
            num /= 10;
        } while (num > 0);
        if (isNegative)
        {
            buffer[i++] = '-';
        }
        buffer[i] = '\0';
        // Reverse the string and send
        int j;
        for (j = i - 1; j >= 0; j--)
        {
            UART_SendChar(buffer[j]);
        }
    #endif
}
References UART_SendChar().
Referenced by decodeBitStream2Seconds(), and UART_SendTime().
UART_SendString()
void UART_SendString (char * str)
send a full string to host system
Parameters
*str,pointer to the string
Returns
void
Definition at line 51 of file uart.c.
{
    #ifdef UART_ENABLED
        while (*str)
        {
            UART_SendChar(*str++);
        }
    #endif
}
References UART_SendChar().
Referenced by checkBitStream(), decodeBitStream2Seconds(), main(), stepperAdvance(), and UART_SendTime().
UART_SendTime()
void UART_SendTime (uint32_t seconds)
Sends a time formated in hours and minutes to host system.
Parameters
seconds,the time in seconds to send
Returns
void
Definition at line 136 of file uart.c.
{
    #ifdef UART_ENABLED
        int hours = (seconds / 3600) % 24;   // Get hours (mod 24 to avoid overflow)
        int minutes = (seconds % 3600) / 60; // Get minutes
    //    UART_SendString("time: ");
        UART_SendInt(hours);
        UART_SendString(":");
        UART_SendInt(minutes);
        UART_SendString("\r\n");
    #endif
}
References UART_SendInt(), and UART_SendString().
Referenced by decodeBitStream2Seconds(), main(), and stepperAdvance().
UART_SendUint32()
void UART_SendUint32 (uint32_t num)
send a 32 bit integer to host system
Parameters
num,the integer to send
Returns
void
Definition at line 107 of file uart.c.
{
    #ifdef UART_ENABLED
        char buffer[11];  // Enough for "4294967295\0"
        int i = 0;
        // Convert integer to string (reverse order)
        do
        {
            buffer[i++] = (num % 10) + '0';
            num /= 10;
        } while (num > 0);
        buffer[i] = '\0';
        // Reverse the string and send
        int j;
        for (j = i - 1; j >= 0; j--)
        {
            UART_SendChar(buffer[j]);
        }
    #endif
}
References UART_SendChar().
Referenced by stepperAdvance().