Flipklok: Code/main.c File Reference
main.c File Reference
Startup of system.
#include <msp430.h>
#include "pins.h"
#include "gpio.h"
#include "clock.h"
#include "timer.h"
#include "adc.h"
#include "stepperAdvance.h"
#include "fwdButton.h"
#include "dcfReceive.h"
#include "led.h"
#include "timeKeeping.h"
#include "pinInterrupts.h"
#include "uart.h"
#include "storeLoadMechanicalTime.h"
Functions
void main (void)
Main function that initializes system components and enters low-power mode.
Variables
uint32_t setTime
uint32_t loaded_value
Detailed Description
Startup of system.
Definition in file main.c.
Function Documentation
main()
void main (void)
Main function that initializes system components and enters low-power mode.
This function is responsible for setting up various system components, including the GPIO, ADC, clocks, and timekeeping system. It also loads the mechanical time from flash memory (if it is connected to a debugger the flash is cleared and the mechanical time must be set manually). It also initializes the UART (if enabled). Additionally, the function sets the time of the mechanical clock and enters low-power mode with interrupts enabled. The system performs various initialization tasks to ensure the proper operation of the application.
It performs the following steps:
Stops the watchdog timer to prevent system reset.
Initializes UART if UART_ENABLED is defined.
Sets up GPIO, ADC, clocks, and timekeeping.
Writes the stored mechanical time from flash to UART.
If the value is invalid because the debugger overwritten the flash, enters an infinite loop.
Configures timers and enters low-power mode with interrupts.
Note
If UART is enabled, a warning will be displayed that the UART will be initialized.
Definition at line 54 of file main.c.
{
    WDTCTL = WDTPW | WDTHOLD;       // stop watchdog timer
    FCTL2 = FWKEY + FSSEL0 + FN1;             // MCLK/3 for Flash Timing Generator
    #ifdef UART_ENABLED
        #warning("Warning: UART is enabled! disable define of UART_ENABLED to disable it.")
        UART_Init();  // Initialize UART
    #endif
    setupGpio();
    setupAdc();
    setupClocks();
    resetTimeKeeping();
    //For testing, setting time of mechanical clock
    uint32_t setMinute = 44;
    uint32_t setHour = 17;
    setTime = setHour * 3600 + setMinute * 60;
    write_SegD(setTime);                    // Write 32-bit value to segment C, increment value
    __delay_cycles(100000);
    loaded_value = load_from_flash(); // Load the value from flash
    if (loaded_value == 0xFFFFFFFF)
    {
        __delay_cycles(100000);
        __no_operation();
        while(1)
        {
            __no_operation();
        }
    }
    __delay_cycles(100000); //wait time otherwise to quick between writing and reading from flash
    mechanicalTimeFloat = loaded_value;
    timeOfLastDcfMessage = mechanicalTimeFloat; // Set the time of DCF before any message received the same as mechanical time so the clock does not stand still at startup
    #ifdef UART_ENABLED
        UART_SendString("\r\n------Starting------\r\n");
        UART_SendString("mechanicalTime: ");
        UART_SendTime(mechanicalTimeFloat);
    #endif
    setupTimer0();
    setupTimer1();
    __bis_SR_register(LPM3_bits | GIE);
}
References load_from_flash(), loaded_value, mechanicalTimeFloat, resetTimeKeeping(), setTime, setupAdc(), setupClocks(), setupGpio(), setupTimer0(), setupTimer1(), timeOfLastDcfMessage, UART_Init(), UART_SendString(), UART_SendTime(), and write_SegD().
Variable Documentation
loaded_value
uint32_t loaded_value
Definition at line 33 of file main.c.
Referenced by load_from_flash(), and main().
setTime
uint32_t setTime
Definition at line 32 of file main.c.
Referenced by main().