Flipklok: Code/include/storeLoadMechanicalTime.h File Reference
storeLoadMechanicalTime.h File Reference
#include <stdint.h>
Functions
void write_SegD (uint32_t value)
Function to write a 32-bit value to Flash segment D for storing the mechanical time, gets called from main() and at the end of stepperAdvance()
uint32_t load_from_flash (void)
Function to load a 32-bit value from Flash memory segment D used for restoring the mechanical time on startup, gets called from main().
Function Documentation
load_from_flash()
uint32_t load_from_flash (void)
Function to load a 32-bit value from Flash memory segment D used for restoring the mechanical time on startup, gets called from main().
Returns
uint32_t the value that is stored in flash
Definition at line 92 of file storeLoadMechanicalTime.c.
{
  uint32_t *Flash_ptr;                         // Pointer to read from Flash memory
  uint32_t loaded_value;
  Flash_ptr = (uint32_t *) 0x1000;             // Point to the start of Flash segment D
  loaded_value = *Flash_ptr;                   // Read the 32-bit value from Flash
  return loaded_value;
}
References loaded_value.
Referenced by main().
write_SegD()
void write_SegD (uint32_t value)
Function to write a 32-bit value to Flash segment D for storing the mechanical time, gets called from main() and at the end of stepperAdvance()
Parameters
[in] value The value to be stored in flash
Definition at line 62 of file storeLoadMechanicalTime.c.
{
  uint32_t *Flash_ptr;                          // Flash pointer
  unsigned int i;
  Flash_ptr = (uint32_t *) 0x1000;             // Initialize Flash pointer (for 32-bit writes)
  FCTL1 = FWKEY + ERASE;                       // Set Erase bit
  FCTL3 = FWKEY;                               // Clear Lock bit
  *Flash_ptr = 0;                              // Dummy write to erase Flash segment
  FCTL1 = FWKEY + WRT;                         // Set WRT bit for write operation
  *Flash_ptr--;
  for (i = 0; i < 8; i++)                     // Write 32-bit value to flash (16 writes per 64 bytes)
  {
    *Flash_ptr = value;                      // Write 32-bit value to flash
    *Flash_ptr++;
  }
//  *Flash_ptr = value;                      // Write 32-bit value to flash
  FCTL1 = FWKEY;                               // Clear WRT bit
  FCTL3 = FWKEY + LOCK;                        // Set LOCK bit
}
Referenced by main(), and stepperAdvance().